### ISSUE TITLE
Add WVS

### ISSUE THREAD

**Issue by jrnold** [winklers/language_lgbt#5]
Add World Values Survey. Not sure whether the most recent wave, or longitudinal data should be used. See which version Chen uses.  Also see how he matches languages to WVS respondents.

**Comment by jrnold** [comment]
I've added files to `data-raw/wvs` with the longitudinal waves.  The languages for the WVS have already been linked to WALS by [Linking the World Values Survey to the World
Atlas of Language Structures](http://journals.plos.org/plosone/article/asset?unique&id=info:doi/10.1371/journal.pone.0132145.s009) by Sean Roberts for a PLOS One article. These were linked to http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4506144/.

**Comment by jrnold** [comment]
@winklers Do you want to take a look at this and see how feasible it is to merge them? Are there good questions on opinions towards homosexuality in WVS?

**Comment by winklers** [comment]
The question on homsexuality in WVS follows the same premise as Afrobarometer. It asks, out of a list, which of these would you not want as a neighbor? And then it codes as 'mentioned' if homosexuality is one of the respondents' answers. WVS has this data on multiple countries going back to Wave 2 (1990)-- but there are several countries with missing data on this variable in certain waves, and WVS only covers 9 African countries. 

Chen uses 3 waves of WVS (from 1994-2007), because the previous waves didn't ask the respondent which language they primarily speak at home. Most of Chen's analysis relies on the dominant language spoken in a country. When existing sources didn't code a language with his independent variable (future tense), Chen relied on alternative linguistic sources (listed in Appendix B) and only coded for a tense when both a 'cross-linguistic study and a language specific reference' agreed on the language tense structure. He discusses a handful of African languages as ones that were not coded, and provides the sources he used to manually code -- so we can likely use these for a few of our African languages to do manual matching. 

We could use the WVS to WALS matching that you linked to above as a way to pick up a few additional matches to our Afrobarometer languages. But, right now WVS only has 4 of the Afrobarometer countries we are working with so it won't add many matches. 

I can share a few more thoughts re: WALS v Afrobarometer on Wednesday.
